### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by walter211** [gliheng/flutter-app-demo#2]
Traceback (most recent call last):
  File "scripts/run.py", line 55, in <module>
    cwd = PROJ_DIR, check = True)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'flutter': 'flutter'

**Comment by ghost** [comment]
it looks like the issue come from you have not `flutter` installed.

Does running `flutter` in your shell work?
